### ISSUE TITLE
Upgrading to latest python-markdown breaks tests

### ISSUE THREAD

**Issue by eykd** [Crossway/antimarkdown#5] opened 2017-03-02 16:47 UTC
While setting up Travis-CI, I noticed that upgrading to `Markdown==2.6.8` causes some of the tests to break. There must be some behavior changes between the 2.5.x and 2.6.x. series.

**Comment by ryanmrubin** [comment] 2017-05-12 14:24
I was messing with this, and reproduced the failures if I only upgraded `Markdown`, but not if I also upgraded `html5lib`. There's a comment in there that the 7-9s version of `html5lib` is required for html5tidy, but is that true, since upgrading it does not cause any tests to fail and indeed fixes the test failures caused by upgrading `markdown`?

**Comment by ryanmrubin** [comment] 2017-05-12 14:29
NEVER MIND my virtualenv was in a weird and not-reproducible state. Not sure what happened there.

**Comment by dwickwire** [comment] 2017-06-28 09:26
Is this still an issue or was it closed by #8

**Comment by ryanmrubin** [comment] 2017-06-28 13:51
This is still an issue. One test fails on the new version of Markdown. I was thinking about looking into it today.

**Closed** 2017-06-28 15:42 UTC
Labels: bug
